name: Build and Deploy Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run Tests
        run: |
          pip install pytest
          pytest

      # Step 5: Create build output (e.g., package files)
      - name: Create Build Output
        run: |
          mkdir build
          cp requirements.txt build/
          echo "Build completed successfully." > build/build-info.txt

      # Step 6: Upload build output as an artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download the build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: downloaded-build

      # Step 2: Deploy to AWS S3 (example)
      - name: Deploy to AWS S3
        run: |
          aws s3 cp downloaded-build/ s3://your-bucket-name/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Optional: Deploy to FTP Server (example)
      - name: Deploy to FTP Server
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp.yourserver.com <<EOF
          mirror -R downloaded-build/ /remote/path/
          quit
          EOF
