name: Artifact Example Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-artifact:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Generate a sample file
      - name: Generate Output File
        run: echo "This is the content of the output file." > output.txt

      # Step 3: Upload the file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: output.txt

  process-artifact:
    runs-on: ubuntu-latest
    needs: generate-artifact

    steps:
      # Step 1: Download the artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact

      # Step 2: Process the downloaded file
      - name: Process Artifact
        run: |
          cat output.txt
          echo "Artifact processed successfully."
