name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run Tests
        run: |
          pip install pytest
          pytest

      # Step 5: Create build output (e.g., package files)
      - name: Create Build Output
        run: |
          mkdir build
          cp requirements.txt build/
          echo "Build completed successfully." > build/build-info.txt

      # Step 6: Upload build output as an artifact (using v4)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/

  download:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download the build artifact (using v4)
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: downloaded-build

      # Step 2: Verify downloaded artifact
      - name: Verify Downloaded Artifact
        run: |
          ls -R downloaded-build
          cat downloaded-build/build-info.txt
